# Example Site settings

#google_analytics: UA-NNNNNNNN-N

#header_pages:
#  - index.md
#  - about.md

#footer: 'follow us on <a href="https://twitter.com/">twitter</a>'

plugins:
  - jekyll-seo-tag

# Theme options
# style: dark # dark (default) or light or hacker
# listen_for_clients_preferred_style: true # true or false (default)

# Fonts
# disable_google_fonts: false # set true to prevent loading fonts.googleapis.com
